version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  node:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysecretpassword
      DB_NAME: mydatabase
    depends_on:
      - db

